### ISSUE TITLE
Generate meta data

### ISSUE THREAD

**Issue by ww2470** [yipenglai/Action-Potential-Analyzer#2]
- [ ] Count action potentials by sweep
- [ ] Rheobase statistics: rheobase (current level), threshold
- [ ] First sweep that reaches the max number of action potentials: halfwidth, max trace, and max rate for the first and last action potential
